/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-30 06:57:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cocktailTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cocktailTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688650288722L));
    _jspx_dependants.put("jar:file:/Users/imilae/SemiProject-MixologyConnect/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>칵테일 추천</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/cocktailTest.css\">\n");
      out.write("    <link href=\"https://fonts.cdnfonts.com/css/segoe-ui-4\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a5af36132e.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"banner\">\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/칵테일.png\" alt=\"\"><p>칵테일취향 테스트</p> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/칵테일2.png\">\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("    <main>\n");
      out.write("\n");
      out.write("        <div class=\"text\">\n");
      out.write("\n");
      out.write("            \n");
      out.write("            <pre>\n");
      out.write("                술자리 유형으로 알아보는 칵테일 추천!!\n");
      out.write("\n");
      out.write("                    나에게 맞는 칵테일을 찾아보세요.\n");
      out.write("            </pre>\n");
      out.write("\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/술자리 이미지.jpeg\">\n");
      out.write("\n");
      out.write("            <br><br>\n");
      out.write("\n");
      out.write("            <button id=\"btn\">칵테일 취향 테스트 시작하기!</button>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("       \n");
      out.write("        <!-- 첫번째 공통질문 -->\n");
      out.write("        <div class=\"q1\">\n");
      out.write("\n");
      out.write("            <div class=\"slide\">\n");
      out.write("                <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"10\" class=\"range\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"btn\">\n");
      out.write("                <button class=\"back-re\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">1/3</span>\n");
      out.write("            </div> \n");
      out.write("            <div class=\"content\">\n");
      out.write("                <div class=\"question\">Q.1</div>\n");
      out.write("                <div>술자리에서 즐겨마시는 술은?</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"choice\">\n");
      out.write("                <div><button class=\"soju-btn\">소주</button></div>\n");
      out.write("                <div><button class=\"beer-btn\">맥주</button></div>\n");
      out.write("                <div><button class=\"non-btn\">이슬톡톡</button></div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 소주 관련 질문 -->\n");
      out.write("        <div class=\"q1-soju\">\n");
      out.write("    \n");
      out.write("            <div class=\"q1-2\">\n");
      out.write("\n");
      out.write("                <div class=\"slide\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"20\" class=\"range\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn\">\n");
      out.write("                    <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/3</span>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"question\">Q.2</div>\n");
      out.write("                    <div>나의 주량은?</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"choice\">\n");
      out.write("                    <div><button class=\"q2-btn\">소주 1병 이하,,</button></div>\n");
      out.write("                    <div><button class=\"q2-btn\">소주 2병까지는 가능~</button></div>\n");
      out.write("                    <div><button class=\"q2-btn\">소주 3병 이상 ㄷㄷ</button></div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"q1-3\">\n");
      out.write("    \n");
      out.write("                <div class=\"slide\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"30\" class=\"range\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn\">\n");
      out.write("                    <button class=\"back-3\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/3</span>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"question\">Q.3</div>\n");
      out.write("                    <div>새콤달콤 달달한 칵테일? VS 청량한 탄산감있는 칵테일?</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"choice\">\n");
      out.write("                    <div><button class=\"q3-sojusweet-btn\">달달</button></div>\n");
      out.write("                    <div><button class=\"q3-sojucoke-btn\">청량</button></div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("       <!-- --------------------------------------------------------------------------------------------- --> \n");
      out.write("        \n");
      out.write("        <!-- 맥주 관련 질문 -->\n");
      out.write("        <div class=\"q2-beer\">\n");
      out.write("\n");
      out.write("            <div class=\"q2-2\">\n");
      out.write("\n");
      out.write("                <div class=\"slide\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"20\" class=\"range\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn\">\n");
      out.write("                    <button class=\"back-beer\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/3</span>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"question\">Q.2</div>\n");
      out.write("                    <div>나의 주량은?</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"choice\">\n");
      out.write("                    <div><button class=\"q2-1-btn\">생맥 500기준 3잔이하</button></div>\n");
      out.write("                    <div><button class=\"q2-1-btn\">3잔은 거뜬</button></div>\n");
      out.write("                    <div><button class=\"q2-1-btn\">맥주먹고 취한적 없음</button></div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"q2-3\">\n");
      out.write("    \n");
      out.write("                <div class=\"slide\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"30\" class=\"range\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn\">\n");
      out.write("                    <button class=\"back-3\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/3</span>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"question\">Q.3</div>\n");
      out.write("                    <div>좋아하는 맥주 종류는?</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"choice\">\n");
      out.write("                    <div><button class=\"q3-1-btn\">흑맥주</button></div>\n");
      out.write("                    <div><button class=\"q3-2-btn\">라거</button></div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- ------------------------------------------------------------------------------------- -->\n");
      out.write("\n");
      out.write("        <!-- 이슬톡톡 관련 질문 -->\n");
      out.write("\n");
      out.write("        <div class=\"q3-non\">\n");
      out.write("\n");
      out.write("            <div class=\"q3-2\">\n");
      out.write("\n");
      out.write("                <div class=\"slide\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"20\" class=\"range\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn\">\n");
      out.write("                    <button class=\"back-beer\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/3</span>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"question\">Q.2</div>\n");
      out.write("                    <div>나의 주량은?</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"choice\">\n");
      out.write("                    <div><button class=\"q3-q-btn\">이슽톡톡 1캔</button></div>\n");
      out.write("                    <div><button class=\"q3-q-btn\">이슬톡톡 먹고 취하지는 않음!</button></div>\n");
      out.write("                    <div><button class=\"q3-q-btn\">소주 반병은 가능</button></div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"q3-3\">\n");
      out.write("    \n");
      out.write("                <div class=\"slide\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"30\" class=\"range\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn\">\n");
      out.write("                    <button class=\"back-3\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/3</span>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"question\">Q.3</div>\n");
      out.write("                    <div>새콤달콤 달달한 칵테일? VS 청량한 탄산감있는 칵테일?</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"choice\">\n");
      out.write("                    <div><button class=\"q3-3-1-btn\">달달</button></div>\n");
      out.write("                    <div><button class=\"q3-3-2-btn\">청량</button></div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- ------------------------------------ 로딩화면--------------------------------------- -->\n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        <div class=\"loading-page\">\n");
      out.write("\n");
      out.write("            \n");
      out.write("            <div id=\"loading-word\">결과 분석중..</div>\n");
      out.write("            <div class=\"loading\">\n");
      out.write("                <span></span>\n");
      out.write("                <span></span>\n");
      out.write("                <span></span>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- ------------------------------------- 칵테일 결과(18가지) --------------------------------------------------- -->\n");
      out.write("        <!-- result 1~3 : 소주-달달(파우스트, 블랙러시안, 롱아일랜드 아이스티)\n");
      out.write("            \n");
      out.write("\n");
      out.write("             \n");
      out.write("            \n");
      out.write("\n");
      out.write("             \n");
      out.write("             \n");
      out.write("        -->\n");
      out.write("\n");
      out.write("        <div class=\"result1\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/갓파더.png\"></div>\n");
      out.write("                <div>파우스트</div>\n");
      out.write("                <div>진한 위스키와 달콤한 향, 달짝지근한 끝맛을 좋아하는 분들에게 추천! <br><br>\n");
      out.write("                    약 20-30도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"result2\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/블랙러시안.png\"></div>\n");
      out.write("                <div>블랙러시안</div>\n");
      out.write("                <div>위스키 베이스로, 칵테일의 여왕이라는 별칭을 가지고 있는 칵테일이다. 스위트 베르무트가 들어가 달콤한 맛을 지니고 있다.<br><br>\n");
      out.write("                    약 30도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"result3\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/롱아일랜드 아이스티.png\"></div>\n");
      out.write("                <div>롱아일랜드 아이스티</div>\n");
      out.write("                <div>쿠바의 전통 음료, 달달함과 동시에 민트 향을 내면서 씁쓸한 뒷맛이 스쳐가니 나름 입체적인 맛이라 할 수 있다.<br><br>\n");
      out.write("                    약 10-20도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("		\n");
      out.write("		<!--  result 4~6 : 소주-술맛(갓파더, 사제락, 카타르시스) -->\n");
      out.write("        <div class=\"result4\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/갓파더.png\"></div>\n");
      out.write("                <div>갓파더</div>\n");
      out.write("                <div> 실제로 영화 '대부'를 기념하여 만들어진 칵테일이라고 한다. '갓파더'는 강렬한 위스키의 첫맛에 달달하고 향긋한 아마레또의 향으로 마무리된다. 알콜 도수는 30도 중반대로 높은 편이다.  <br><br>\n");
      out.write("                    약 30-40도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"result5\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/사제락.png\"></div>\n");
      out.write("                <div>사제락</div>\n");
      out.write("                <div>미국 역사상 가장 오래된 칵테일로 일컬어지는 사제락(Sazerac). 상큼한 레몬 풍미와 상쾌한 허브, 향긋한 아니스, 부드러운 질감과 은은한 단맛이 환상적인 밸런스를 이룬다.  <br><br>\n");
      out.write("                    약 40-45도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"result6\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/카타르시스.png\"></div>\n");
      out.write("                <div>카타르시스</div>\n");
      out.write("                <div>카타르시스는 오버루프 럼, 아마레또, 라임 주스를 빌드해서 만드는 칵테일로, 재료도 간단하고 만드는 방법도 간단해서 쉽게 만들어 마실 수 있는 칵테일입니다! 하지만 오버루프럼이 들어가는 만큼 도수도 높다는 점!<br><br>\n");
      out.write("                    약 50-55도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- result 7~9 : 맥주-흑맥주(블랙 벨벳, 더티호, 행맨스 블러드) -->\n");
      out.write("        <div class=\"result7\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/블랙벨벳.png\"></div>\n");
      out.write("                <div>블랙 벨벳</div>\n");
      out.write("                <div>블랙 벨벳은 발포성 포도주 또는 스타우트(주로 기네스)를 기반으로 하는 맥주 칵테일이다. 샴페인의 고급스러운 청량감과 단맛이 먼저 느껴지고, 이후 스타우트 흑맥주의 쌉싸름한 맛이 뒷맛으로 남는 정말 고급스러운 칵테일!  <br><br>\n");
      out.write("                    약 10도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"result8\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/더티호.png\"></div>\n");
      out.write("                <div>더티호</div>\n");
      out.write("                <div>아일랜드산 흑맥주인 기네스와 벨기에산 맥주인 호가든 이 두가지 맥주를 1:1로 섞어서 층을 만드는 맥주 플로팅 칵테일의 일종이다. 여담으로 각각의 맥주는 호가든 4.9도, 기네스 4.4도로 높진 않지만, 두 잔 정도 더티호로 만들어 먹으면 꽤나 빨리 취기가 올라온다. 이 점 유념하고 마시자. <br><br>\n");
      out.write("                    약 5도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"result9\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/행맨스블러드.png\"></div>\n");
      out.write("                <div>행맨스 블러드</div>\n");
      out.write("                <div>브랜디의 맛과 흑맥주의 맛이 강하게 나는 칵테일. 진, 럼, 위스키, 브랜디, 와인, 흑맥주 등 거의 모든 양주를 다 베이스로 하는 칵테일로, 그 기원은 영국이라고 한다. <br><br>\n");
      out.write("                    약 10-20도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!--  result 10~12 : 맥주-라거(레드아이, 샌디 개프, 소맥) -->\n");
      out.write("        <div class=\"result10\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/레드아이.png\"></div>\n");
      out.write("                <div>레드아이</div>\n");
      out.write("                <div>맥주와 토마토 주스를 이용한 칵테일. 토마토 주스 맛이 나지만 맥주를 베이스로 한다. 도수는 3도 정도. 숙취해소용 칵테일이며 여성, 남성 가릴 것 없이 숙취해소용으로 가볍게 마시면 좋다. <br><br>\n");
      out.write("                    약 3도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"result11\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/샌디개프.png\"></div>\n");
      out.write("                <div>샌디 개프</div>\n");
      out.write("                <div>맥주 베이스로, 맥주와 진저에일을 절반씩 섞어 만드는 칵테일이다. 맛은 진저에일의 생강 향, 약간의 단 맛과 맥주의 씁쓸한 맛이 조화를 이룬다. 이탈리아로부터 역사가 아주 긴 칵테일이라 전해진다.  <br><br>\n");
      out.write("                    약 5도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <div class=\"result12\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/소맥.png\"></div>\n");
      out.write("                <div>소맥</div>\n");
      out.write("                <div>소주와 맥주를 섞은 칵테일의 일종. 대한민국 성인이라면 안먹어 본 사람은 있어도 한번만 먹어본 사람은 없다는 우리나라 대표 칵테일! <br><br>\n");
      out.write("                    약 10-20도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- result 13~15 : 이슬 달달(피치크러쉬, 준벅, 미도리 사워) -->\n");
      out.write("        <div class=\"result13\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/피치크러쉬.png\"></div>\n");
      out.write("                <div>피치크러쉬</div>\n");
      out.write("                <div>복숭아 향과 맛이 느껴지는 피치 리큐르에 크랜베리 주스를 섞어 만든 칵테일로 복숭아와 크렌베리의 새콤한 향과 맛의 어우러짐을 특징으로 가지고 있는 칵테일! <br><br>\n");
      out.write("                    약 5도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"result14\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/준벅.png\"></div>\n");
      out.write("                <div>준벅</div>\n");
      out.write("                <div>6월의 푸르름을 표현한 칵테일. 향과 맛이 달콤하기로 유명한 리큐르인 말리부가 들어가서 달달한 맛을 보여주는 칵테일!  <br><br>\n");
      out.write("                    약 5-10도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"result15\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/미도리사워.png\"></div>\n");
      out.write("                <div>미도리 사워</div>\n");
      out.write("                <div>멜론 리큐르의 한 종류인 미도리를 사용해 만드는 유명한 칵테일이다. 멜론맛인 미도리와 스윗&사워 믹스의 레몬향이 어우러져서 상큼한 색깔과 맛을 연출하는 것이 포인트. <br><br>\n");
      out.write("                    약 5-10도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- result 16~18 : 이슬 청량(모히토, 팔로마, 산토리 하이볼) -->\n");
      out.write("        <div class=\"result16\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/모히토.png\"></div>\n");
      out.write("                <div>모히토</div>\n");
      out.write("                <div>럼 베이스 칵테일. 맛은 달달함과 동시에 민트 향을 내면서 씁쓸한 뒷맛이 스쳐가니 나름 입체적인 맛이라 할 수 있다.<br><br>\n");
      out.write("                    약 10-20도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"result17\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/팔로마.png\"></div>\n");
      out.write("                <div>팔로마</div>\n");
      out.write("                <div>데킬라 베이스로 하며, 높은 청량감과 가벼운 알코올 도수 덕분에 더운 여름에 마시기 적합한 음료라고 할 수 있습니다.<br><br>\n");
      out.write("                    약 10-20도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"result18\">\n");
      out.write("            <div class=\"cocktail\">\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cocktailTest/산토리하이볼.png\"></div>\n");
      out.write("                <div>산토리 하이볼</div>\n");
      out.write("                <div>산토리 하이볼은 일식 이자카야에서도 흔히 찾을 수  있는 유명한 칵테일이죠. 상큼하고 달달한 맛으로 인기를 끌고있는 일본의 산토리 위스키! <br><br>\n");
      out.write("                    약 20-30도\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div> <br>\n");
      out.write("            <div class=\"reset\">\n");
      out.write("\n");
      out.write("                <button>테스트 다시하기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/cocktailTest.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
