/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-24 12:07:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cocktailTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cocktailTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1689072618969L));
    _jspx_dependants.put("jar:file:/C:/Users/jy041/Documents/SemiProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>칵테일 추천</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/cocktailTest.css\">\r\n");
      out.write("    <link href=\"https://fonts.cdnfonts.com/css/segoe-ui-4\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a5af36132e.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"banner\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/칵테일.png\" alt=\"\"><p>칵테일취향 테스트</p> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/칵테일2.png\">\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <main>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <pre>\r\n");
      out.write("                술자리 유형으로 알아보는 칵테일 추천!!\r\n");
      out.write("\r\n");
      out.write("                    나에게 맞는 칵테일을 찾아보세요.\r\n");
      out.write("            </pre>\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("resources/images/술자리 이미지.jpeg\">\r\n");
      out.write("\r\n");
      out.write("            <br><br>\r\n");
      out.write("\r\n");
      out.write("            <button id=\"btn\">칵테일 취향 테스트 시작하기!</button>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <!-- 첫번째 공통질문 -->\r\n");
      out.write("        <div class=\"q1\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"slide\">\r\n");
      out.write("                <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"10\" class=\"range\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn\">\r\n");
      out.write("                <button class=\"back-re\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">1/3</span>\r\n");
      out.write("            </div> \r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.1</div>\r\n");
      out.write("                <div>좋아하는 술은?</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"choice\">\r\n");
      out.write("                <div><button class=\"soju-btn\">소주</button></div>\r\n");
      out.write("                <div><button class=\"beer-btn\">맥주</button></div>\r\n");
      out.write("                <div><button class=\"non-btn\">이슬톡톡</button></div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 소주 관련 질문 -->\r\n");
      out.write("        <div class=\"q1-soju\">\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"q1-2\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"20\" class=\"range\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/3</span>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"question\">Q.2</div>\r\n");
      out.write("                    <div>나의 주량은?</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"choice\">\r\n");
      out.write("                    <div><button class=\"q2-btn\">소주 1병 이하,,</button></div>\r\n");
      out.write("                    <div><button class=\"q2-btn\">소주 2병까지는 가능~</button></div>\r\n");
      out.write("                    <div><button class=\"q2-btn\">소주 3병 이상 ㄷㄷ</button></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"q1-3\">\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"30\" class=\"range\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <button class=\"back-3\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/3</span>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"question\">Q.3</div>\r\n");
      out.write("                    <div>달달한거 청량한거</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"choice\">\r\n");
      out.write("                    <div><button class=\"q3-sojusweet-btn\">달달</button></div>\r\n");
      out.write("                    <div><button class=\"q3-sojucoke-btn\">청량</button></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("       <!-- --------------------------------------------------------------------------------------------- --> \r\n");
      out.write("        \r\n");
      out.write("        <!-- 맥주 관련 질문 -->\r\n");
      out.write("        <div class=\"q2-beer\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q2-2\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"20\" class=\"range\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <button class=\"back-beer\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/3</span>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"question\">Q.2</div>\r\n");
      out.write("                    <div>나의 주량은?</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"choice\">\r\n");
      out.write("                    <div><button class=\"q2-1-btn\">생맥 500기준 3잔이하</button></div>\r\n");
      out.write("                    <div><button class=\"q2-1-btn\">3잔은 거뜬</button></div>\r\n");
      out.write("                    <div><button class=\"q2-1-btn\">맥주먹고 취한적 없음</button></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"q2-3\">\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"30\" class=\"range\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <button class=\"back-3\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/3</span>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"question\">Q.3</div>\r\n");
      out.write("                    <div>좋아하는 맥주 종류는?</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"choice\">\r\n");
      out.write("                    <div><button class=\"q3-1-btn\">흑맥주</button></div>\r\n");
      out.write("                    <div><button class=\"q3-2-btn\">라거</button></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ------------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("        <!-- 이슬톡톡 관련 질문 -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"q3-non\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q3-2\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"20\" class=\"range\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <button class=\"back-beer\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/3</span>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"question\">Q.2</div>\r\n");
      out.write("                    <div>나의 주량은?</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"choice\">\r\n");
      out.write("                    <div><button class=\"q3-q-btn\">이슽톡톡 1캔</button></div>\r\n");
      out.write("                    <div><button class=\"q3-q-btn\">이슬톡톡 먹고 취하지는 않음!</button></div>\r\n");
      out.write("                    <div><button class=\"q3-q-btn\">소주 반병은 가능</button></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"q3-3\">\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"30\" step=\"10\" value=\"30\" class=\"range\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn\">\r\n");
      out.write("                    <button class=\"back-3\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/3</span>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"question\">Q.3</div>\r\n");
      out.write("                    <div>달달한거 청량한거</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"choice\">\r\n");
      out.write("                    <div><button class=\"q3-3-1-btn\">달달</button></div>\r\n");
      out.write("                    <div><button class=\"q3-3-2-btn\">청량</button></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- ------------------------------------ 로딩화면--------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"loading-page\">\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"loading-word\">결과 분석중");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("            <div class=\"loading\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ------------------------------------- 칵테일 결과(18가지) --------------------------------------------------- -->\r\n");
      out.write("        <!-- result 1~3 : 소주-달달(파우스트, 블랙러시안, 롱아일랜드 아이스티)\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("             \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("        -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result1\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/갓파더.webp\"></div>\r\n");
      out.write("                <div>파우스트</div>\r\n");
      out.write("                <div>진한 위스키와 달콤한 향, 달짝지근한 끝맛을 좋아하는 분들에게 추천! <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result2\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/맨해튼(칵테일).jpg\"></div>\r\n");
      out.write("                <div>블랙러시안</div>\r\n");
      out.write("                <div>위스키 베이스로, 칵테일의 여왕이라는 별칭을 가지고 있는 칵테일이다. 스위트 베르무트가 들어가 달콤한 맛을 지니고 있다.<br><br>\r\n");
      out.write("                    약 30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result3\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/모히토.jpg\"></div>\r\n");
      out.write("                <div>롱아일랜드 아이스티</div>\r\n");
      out.write("                <div>쿠바의 전통 음료, 달달함과 동시에 민트 향을 내면서 씁쓸한 뒷맛이 스쳐가니 나름 입체적인 맛이라 할 수 있다.<br><br>\r\n");
      out.write("                    약 10-20도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("		\r\n");
      out.write("		<!--  result 4~6 : 소주-술맛(갓파더, 사제락, 카타르시스) -->\r\n");
      out.write("        <div class=\"result4\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/코스모폴리탄.jpg\"></div>\r\n");
      out.write("                <div>갓파더</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result5\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/예거밤.webp\"></div>\r\n");
      out.write("                <div>사제락</div>\r\n");
      out.write("                <div>폭발적인 에너지를 느낄 수 있는 예거밤, 파티나 클럽에서 텐션 높이는데 딱 좋은 칵테일이죠! 에너지 드링크의 카페인과 리큐르의 알코올이 만나 입은 행복하지만 위장이 박살나는 무시무시한 칵테일이기도 합니다 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result6\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/김렛.webp\"></div>\r\n");
      out.write("                <div>카타르시스</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- result 7~9 : 맥주-흑맥주(블랙 벨벳, 더티호, 행맨스 블러드) -->\r\n");
      out.write("        <div class=\"result7\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/다이키리.webp\"></div>\r\n");
      out.write("                <div>블랙 벨벳</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result8\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/말리부 밀크.webp\"></div>\r\n");
      out.write("                <div>더티호</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result9\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/아디오스 마더퍼커.webp\"></div>\r\n");
      out.write("                <div>행맨스 블러드</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!--  result 10~12 : 맥주-라거(레드아이, 샌디 개프, 소맥) -->\r\n");
      out.write("        <div class=\"result10\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>레드아이</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result11\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>샌디 개프</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result12\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>소맥</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- result 13~15 : 이슬 달달(피치크러쉬, 준벅, 미도리 사워) -->\r\n");
      out.write("        <div class=\"result13\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>피치크러쉬</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result14\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>준벅</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result15\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>미도리 사워</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- result 16~18 : 이슬 청량(모히토, 팔로마, 산토리 하이볼) -->\r\n");
      out.write("        <div class=\"result16\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>모히토</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result17\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>팔로마</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result18\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/블루하와이안.webp\"></div>\r\n");
      out.write("                <div>산토리 하이볼</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/cocktailTest.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
