/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-24 03:38:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cocktailTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cocktailTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688615096366L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/semiproject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>칵테일 추천</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/cocktailTest.css\">\r\n");
      out.write("    <link href=\"https://fonts.cdnfonts.com/css/segoe-ui-4\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a5af36132e.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"banner\">\r\n");
      out.write("        <img src=\"../img/칵테일.png\" alt=\"\"><p>칵테일취향 테스트</p> <img src=\"../img/칵테일2.png\">\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text\">\r\n");
      out.write("            <pre>\r\n");
      out.write("                술자리 유형으로 알아보는 칵테일 추천!!\r\n");
      out.write("\r\n");
      out.write("                    나에게 맞는 칵테일을 찾아보세요.\r\n");
      out.write("            </pre>\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/술자리 이미지.jpeg\">\r\n");
      out.write("\r\n");
      out.write("            <br><br>\r\n");
      out.write("\r\n");
      out.write("            <button id=\"btn\">칵테일 취향 테스트 시작하기!</button>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        <div class=\"q1\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"range\" min=\"0\" max=\"60\" step=\"10\" value=\"10\" class=\"range\"><br>\r\n");
      out.write("            <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">1/6</span>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.1</div>\r\n");
      out.write("                <div>술 약속이 잡혔다! 내가 원하는 모임장소는?</div>\r\n");
      out.write("                <div><button class=\"q1-btn\">독특한 컨셉으로 유명한 핫플</button></div>\r\n");
      out.write("                <div><button class=\"q1-btn\">분위기 최고! 감성적인 LP바</button></div>\r\n");
      out.write("                <div><button class=\"q1-btn\">사람 많고 음악 뿜뿜 신나는 곳</button></div>\r\n");
      out.write("                <div><button class=\"q1-btn\">편하게 마실 수 있는 집 근처</button></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"q2\">\r\n");
      out.write("            <input type=\"range\" min=\"0\" max=\"60\" step=\"10\" value=\"20\" class=\"range\"><br>\r\n");
      out.write("            <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">2/6</span>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.2</div>\r\n");
      out.write("                <div>모임 장소 도착! 안주는 뭐먹지?</div>\r\n");
      out.write("                <div><button class=\"q2-btn\">귀찮은데 기본 과자 안주나 먹자!</button></div>\r\n");
      out.write("                <div><button class=\"q2-btn\">달콤상콤한 과일안주가 좋지~</button></div>\r\n");
      out.write("                <div><button class=\"q2-btn\">술 안주는 바삭바삭한 튀김이지!</button></div>\r\n");
      out.write("                <div><button class=\"q2-btn\">든든한 식사 메뉴로 반주!</button></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"q3\">\r\n");
      out.write("            <input type=\"range\" min=\"0\" max=\"60\" step=\"10\" value=\"30\" class=\"range\"><br>\r\n");
      out.write("            <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">3/6</span>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.3</div>\r\n");
      out.write("                <div>나의 가장 favourite 폭탄주는?</div>\r\n");
      out.write("                <div><button class=\"q3-btn\">클래식이 최고! 소맥이지</button></div>\r\n");
      out.write("                <div><button class=\"q3-btn\">술에는 탄산음료지! 고진감래주</button></div>\r\n");
      out.write("                <div><button class=\"q3-btn\">새콤달콤 복분자주!</button></div>\r\n");
      out.write("                <div><button class=\"q3-btn\">달달하고 부드러운 메로나주!</button></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"q4\">\r\n");
      out.write("            <input type=\"range\" min=\"0\" max=\"60\" step=\"10\" value=\"40\" class=\"range\"><br>\r\n");
      out.write("            <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">4/6</span>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.4</div>\r\n");
      out.write("                <div>술을 꽤 많이마셨다.. 지금 상태는?</div>\r\n");
      out.write("                <div><button class=\"q4-btn\">기분 업 될만큼 살짝 알딸딸!</button></div>\r\n");
      out.write("                <div><button class=\"q4-btn\">이제부터 쉬어가면서 조금씩 마셔야지!</button></div>\r\n");
      out.write("                <div><button class=\"q4-btn\">술집이 내 집인거마냥 꿈나라행..zzz</button></div>\r\n");
      out.write("                <div><button class=\"q4-btn\">했던 얘기 계속 하기..</button></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"q5\">\r\n");
      out.write("            <input type=\"range\" min=\"0\" max=\"60\" step=\"10\" value=\"50\" class=\"range\"><br>\r\n");
      out.write("            <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">5/6</span>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.5</div>\r\n");
      out.write("                <div>술자리중.. 당신의 타입은?</div>\r\n");
      out.write("                <div><button class=\"q5-btn\">밤새 마시고 첫차 탐</button></div>\r\n");
      out.write("                <div><button class=\"q5-btn\">마셔 마셔 더 마셔! 주체못함</button></div>\r\n");
      out.write("                <div><button class=\"q5-btn\">중간에 아무도 모르게 탈주</button></div>\r\n");
      out.write("                <div><button class=\"q5-btn\">안주 털이범...</button></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"q6\">\r\n");
      out.write("            <input type=\"range\" min=\"0\" max=\"60\" step=\"10\" value=\"60\" class=\"range\"><br>\r\n");
      out.write("            <button class=\"back\"><i class=\"fa-solid fa-play fa-rotate-180\"></i></button> <span class=\"num\">6/6</span>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <div class=\"question\">Q.6</div>\r\n");
      out.write("                <div>술 마신 다음날..당신의 해장 원픽은?</div>\r\n");
      out.write("                <div><button class=\"q6-btn\" id=\"one\">해장은 기름기진거로 해야지! 햄버거</button></div>\r\n");
      out.write("                <div><button class=\"q6-btn\" id=\"two\">해장은 얼큰하고 맵게! 국밥</button></div>\r\n");
      out.write("                <div><button class=\"q6-btn\" id=\"three\">속이 다 풀리는 시원한 국물! 냉면</button></div>\r\n");
      out.write("                <div><button class=\"q6-btn\" id=\"four\">최고의 숙취해소제는..잠 zzz</button></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"loading-page\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"loading\">\r\n");
      out.write("                <div>결과 분석중..</div>\r\n");
      out.write("                <div><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/로딩.gif\"></div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"../img/갓파더.webp\"></div>\r\n");
      out.write("                <div>갓 파더</div>\r\n");
      out.write("                <div>진한 위스키와 달콤한 향, 달짝지근한 끝맛을 좋아하는 분들에게 추천! <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result-two\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"../img/맨해튼(칵테일).jpg\"></div>\r\n");
      out.write("                <div>맨해튼</div>\r\n");
      out.write("                <div>위스키 베이스로, 칵테일의 여왕이라는 별칭을 가지고 있는 칵테일이다. 스위트 베르무트가 들어가 달콤한 맛을 지니고 있다.<br><br>\r\n");
      out.write("                    약 30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"result-three\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"../img/모히토.jpg\"></div>\r\n");
      out.write("                <div>모히토</div>\r\n");
      out.write("                <div>쿠바의 전통 음료, 달달함과 동시에 민트 향을 내면서 씁쓸한 뒷맛이 스쳐가니 나름 입체적인 맛이라 할 수 있다.<br><br>\r\n");
      out.write("                    약 10-20도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result-four\">\r\n");
      out.write("            <div class=\"cocktail\">\r\n");
      out.write("                <div><img style=\"width: 300px;\" src=\"../img/코스모폴리탄.jpg\"></div>\r\n");
      out.write("                <div>코스모폴리탄</div>\r\n");
      out.write("                <div>매혹적인 색깔로 유명한 칵테일, 새콤함에 숨겨진 독한 맛 <br><br>\r\n");
      out.write("                    약 20-30도\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div> <br>\r\n");
      out.write("            <div class=\"reset\">\r\n");
      out.write("\r\n");
      out.write("                <button>테스트 다시하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/cocktailTest.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
