DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(30)		NOT NULL,
	"MEMBER_TEL"	VARCHAR2(11)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(15)		NOT NULL,
	"MEMBER_ADDR"	VARCHAR2(200)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NULL,
	"MEMBER_PROFILE"	VARCHAR2(200)		NULL,
	"MANAGER_CODE"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);


DROP TABLE "BOARD";
DROP TABLE "MEMBER";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE		NULL,
	"READ_COUNT"	NUMBER		NULL,
	"BOARD_ST"	CHAR(1)		NULL,
	"BOARD_CD"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

DROP TABLE "BOARD_TYPE";

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CD"	NUMBER		NOT NULL,
	"BOARD_NM"	VARCHAR2(50)		NOT NULL
);

DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(300)		NULL,
	"REPLY_DT"	DATE	DEFAULT SYSDATE	NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

DROP TABLE "COCKTAIL";

CREATE TABLE "COCKTAIL" (
	"COCK_NO"	NUMBER		NOT NULL,
	"COCK_NM"	VARCHAR2(30)		NOT NULL,
	"RECIPE"	VARCHAR2(1000)		NULL,
	"RECIPE_CONTENT"	VARCHAR2(1000)		NULL,
	"LEVEL"	CHAR(3)		NULL,
	"COCK_CONTENT"	VARCHAR2(4000)		NULL,
	"COCK_IMG"	VARCHAR2(200)		NULL,
	"ACL_LEVEL"	VARCHAR2(30)		NULL
);

DROP TABLE "BOARD_LIKE";

CREATE TABLE "BOARD_LIKE" (
	"LIKE_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

DROP TABLE "FOLLOW";

CREATE TABLE "FOLLOW" (
	"FOLLOW_ID"	NUMBER		NOT NULL,
	"FOLLOWER_NO"	NUMBER		NOT NULL,
	"FOLLOING_NO"	NUMBER		NOT NULL
);

DROP TABLE "CopyOfINGREDIENT";

CREATE TABLE "CopyOfINGREDIENT" (
	"INGR_CODE"	NUMBER		NOT NULL,
	"INGR_NM"	VARCHAR2(30)		NULL,
	"INGR_IMG"	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호(- 미포함)';
COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_PROFILE" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."MANAGER_CODE" IS '관리자 권한';
COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴 여부(Y:탈퇴, N:미탈퇴)';

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "BOARD"."BOARD_DT" IS '작성일';
COMMENT ON COLUMN "BOARD"."MODIFY_DT" IS '마지막 수정일';
COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';
COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글 상태(정상Y, 삭제N)';
COMMENT ON COLUMN "BOARD"."BOARD_CD" IS '게시판 코드';
COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '작성자';

COMMENT ON COLUMN "BOARD_LIKE"."LIKE_NO" IS '좋아요 번호';
COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '좋아요한 회원번호';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CD" IS '게시판 코드';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NM" IS '게시판 이름';

COMMENT ON COLUMN "FOLLOW"."FOLLOW_ID" IS '팔로우 팔로잉';
COMMENT ON COLUMN "FOLLOW"."FOLLOWER_NO" IS '팔로우 회원번호';
COMMENT ON COLUMN "FOLLOW"."FOLLOING_NO" IS '팔로잉 회원번호';

COMMENT ON COLUMN "COCKTAIL"."COCK_NO" IS '칵테일 번호';
COMMENT ON COLUMN "COCKTAIL"."COCK_NM" IS '칵테일 이름';
COMMENT ON COLUMN "COCKTAIL"."RECIPE" IS '레시피';
COMMENT ON COLUMN "COCKTAIL"."RECIPE_CONTENT" IS '레시피 설명';
COMMENT ON COLUMN "COCKTAIL"."LEVEL" IS '난이도';
COMMENT ON COLUMN "COCKTAIL"."COCK_CONTENT" IS '칵테일 설명';
COMMENT ON COLUMN "COCKTAIL"."COCK_IMG" IS '칵테일 사진';
COMMENT ON COLUMN "COCKTAIL"."ACL_LEVEL" IS '도수';

COMMENT ON COLUMN "INGREDIENT"."INGR_CODE" IS '재료 코드';
COMMENT ON COLUMN "INGREDIENT"."INGR_NM" IS '재료 이름';
COMMENT ON COLUMN "INGREDIENT"."INGR_IMG" IS '재료 사진';

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호';
COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';
COMMENT ON COLUMN "REPLY"."REPLY_DT" IS '댓글 작성일';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '작성자';

CREATE SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_MEMBER_NO;

CREATE SEQUENCE SEQ_REPLY_NO;

CREATE SEQUENCE SEQ_INGR_CODE;

CREATE SEQUENCE SEQ_BOARD_LIKE;

CREATE SEQUENCE SEQ_BOARD_CD;

CREATE SEQUENCE SEQ_FOLLOW_ID;

ALTER TABLE BOARD 
ADD PRIMARY KEY(BOARD_NO); --제약조건명을 생략(SYS_XXXXXX)

ALTER TABLE MEMBER 
ADD PRIMARY KEY(MEMBER_NO);


ALTER TABLE BOARD
ADD CONSTRAINT "FK_BOARD_MEMBER"
FOREIGN KEY ("MEMBER_NO")
REFERENCES MEMBER;


ALTER TABLE BOARD_LIKE 
ADD PRIMARY KEY(LIKE_NO);

ALTER TABLE BOARD_TYPE 
ADD PRIMARY KEY(BOARD_CD);

ALTER TABLE  COCKTAIL
ADD PRIMARY KEY(COCK_NO);

ALTER TABLE INGREDIENT 
ADD PRIMARY KEY(INGR_CODE);

ALTER TABLE FOLLOW 
ADD PRIMARY KEY(FOLLOW_ID);

ALTER TABLE REPLY 
ADD PRIMARY KEY(REPLY_NO);

-- 게시판 테이블의 게시판 코드 FK조건 추가 
ALTER TABLE BOARD
ADD CONSTRAINT "FK_BOARD_CD"
FOREIGN KEY ("BOARD_CD")
REFERENCES BOARD_TYPE;

--회원 테이블에 CHECK 제약조건
--아직 실행 안함ㅎㅎㅎㅎ
ALTER TABLE BOARD
ADD CONSTRAINT "CHK_BOARD_ST"
CHECK("BOARD_ST" IN('N','Y'));

-- MEMBER TABLE 비밀번호 컬럼 크기 변경
ALTER TABLE MEMBER
MODIFY MEMBER_PW VARCHAR2(100);

-- 암호화된 비밀번호로 업데이트
commit;