--칵테일 이름 또는 내용 또는 칵테일재료에 특정게시글 보기 
SELECT DISTINCT CKTL_NO, CKTL_NM, CKTL_CONTENT,ACL_LEVEL, SGR_LEVEL, IMG_NO,
    IMG_PATH
FROM COCKTAIL
JOIN COCKTAIL_IMG ON(IMG_NO=CKTL_IMG_NO)
JOIN COCKTAIL_AMOUNT USING (CKTL_NO)
JOIN INGREDIENT USING (INGR_CODE)
WHERE INGR_NAME LIKE '%비행%'
OR CKTL_NM LIKE '%비행%'
OR CKTL_CONTENT LIKE '%비행%';

--검색 키워드가 '달달'OR '단' OR '달달한'인 경우 
SELECT CKTL_NO, CKTL_NM, CKTL_CONTENT,ACL_LEVEL, SGR_LEVEL, IMG_NO,
    IMG_PATH
FROM COCKTAIL
JOIN COCKTAIL_IMG ON(IMG_NO=CKTL_IMG_NO)
WHERE SGR_LEVEL ='상';

--칵테일 키워드가 '높은' OR '강한'인 경우 
SELECT CKTL_NO, CKTL_NM, CKTL_CONTENT,ACL_LEVEL, SGR_LEVEL, IMG_NO,
    IMG_PATH
FROM COCKTAIL
JOIN COCKTAIL_IMG ON(IMG_NO=CKTL_IMG_NO)
WHERE ACL_LEVEL ='상';

--결색 결과에  따른 게시글 목록 조회 

    SELECT ROWNUM RNUM, A. * FROM(
		SELECT BOARD_NO, BOARD_TITLE,BOARD_CONTENT, MEMBER_NM,
		TO_CHAR(BOARD_DT, 'YYYY-MM-DD') AS BOARD_DT, READ_COUNT
		FROM BOARD
		JOIN MEMBER USING(MEMBER_NO)
		WHERE BOARD_ST = 'Y'
        AND (BOARD_TITLE LIKE '%칵테일%'
        OR BOARD_CONTENT LIKE '%칵테일%')
        AND BOARD_CD = 2
		ORDER BY BOARD_NO DESC
        )A;
    






