--칵테일 이름 또는 내용 또는 칵테일재료 에 특정게시글 보기 
SELECT DISTINCT CKTL_NO, CKTL_NM, CKTL_CONTENT,ACL_LEVEL, SGR_LEVEL, IMG_NO,
    IMG_PATH, INGR_NAME
FROM COCKTAIL
JOIN COCKTAIL_IMG ON(IMG_NO=CKTL_IMG_NO)
JOIN COCKTAIL_AMOUNT USING (CKTL_NO)
JOIN INGREDIENT USING (INGR_CODE)
WHERE INGR_NAME LIKE '%아메리카노%'
OR CKTL_NM LIKE '%아메리카노%'
OR CKTL_CONTENT LIKE '%아메리카노%';

--검색 키워드가 '달달'OR '단' OR '달달한'인 경우 
SELECT CKTL_NO, CKTL_NM, CKTL_CONTENT,ACL_LEVEL, SGR_LEVEL, IMG_NO,
    IMG_PATH
FROM COCKTAIL
JOIN COCKTAIL_IMG ON(IMG_NO=CKTL_IMG_NO)
WHERE SGR_LEVEL ='상';

--칵테일 키워드가 '높은' OR '강한'인 경우 
SELECT CKTL_NO, CKTL_NM, CKTL_CONTENT,ACL_LEVEL, SGR_LEVEL, IMG_NO,
    IMG_PATH
FROM COCKTAIL
JOIN COCKTAIL_IMG ON(IMG_NO=CKTL_IMG_NO)
WHERE ACL_LEVEL ='상';

--커뮤니티의 제목과 내용에 키워드가 필요한 경우 
SELECT 





