/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-22 15:43:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688650484420L));
    _jspx_dependants.put("jar:file:/C:/workspace/05_Server/SemiProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!DOCTYPE html>\r\n");
      out.write("		<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("		<head>\r\n");
      out.write("			<meta charset=\"UTF-8\">\r\n");
      out.write("			<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("			<title>상세 게시글</title>\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/boardDatail.css\">\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reply.css\">\r\n");
      out.write("\r\n");
      out.write("			<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"\r\n");
      out.write("				integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("		</head>\r\n");
      out.write("\r\n");
      out.write("		<body style=\"overflow-x: hidden\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"content\">\r\n");
      out.write("					<div class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.boardTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("					<div class=\"name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.boardName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("					<div class=\"date\">\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.boardDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						<div class=\"views\">조회수 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.readCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 게시글 사진, 내용, 좋아요, 공유버튼 있는 칸 -->\r\n");
      out.write("					<!-- 사진 -->\r\n");
      out.write("					<div class=\"img\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"https://static.wixstatic.com/media/6c7c63_6ecbbc371bc34437ab1fff7375bf32af~mv2.jpeg/v1/fill/w_420,h_420,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/6c7c63_6ecbbc371bc34437ab1fff7375bf32af~mv2.jpeg\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 게시글 내용 -->\r\n");
      out.write("					<div class=\"datail\">롱아일랜드 아이스티, 줄여서 '롱티'라고도 자주 불리는 이 칵테일은 달콤한 콜라\r\n");
      out.write("						향에 숨겨진 꽤나 높은 알콜도수를 자랑한답니다. 데킬라, 럼, 보드카 등 다양한 양주가 들어가는 칵테일계의 진정한 폭탄주로\r\n");
      out.write("						많은 사랑을 받고 있죠! 롱티는 미국의 금주법 시대에 만들어진 레시피라는 설이 있답니다. 술을 구하기 어려웠기에 소량으로\r\n");
      out.write("						남았던 술들 종류불문하고 다 넣어서 한 번에 마시기 위해 섞은 것에서부터 시작되었다고 해요. 그래서인지 달콤한 콜라로\r\n");
      out.write("						위장하기 딱 좋은 맛과 외형을 가졌으나, 한 잔으로도 금방 취할 수 있으니 방심은 금물! 1. 글라스에 얼음을 먼저\r\n");
      out.write("						넣는다. 2. 보드카, 데킬라, 진, 럼, 그리고 트리플섹을 먼저 따른 후 사워믹스까지 넣는다. 3. 남은 공간은 콜라로\r\n");
      out.write("						가득 채워준다. 4. 바 스푼으로 천천히 저어주고 웨지 레몬으로 장식한다. Tip: 너무 세게 저으면 콜라의 탄산이 쉽게\r\n");
      out.write("						빠지기 때문에 천천히 저어줘야 함!</div>\r\n");
      out.write("\r\n");
      out.write("					<form>\r\n");
      out.write("						<!-- 좋아요, 북마크 -->\r\n");
      out.write("						<div class=\"share\">\r\n");
      out.write("							<button type=\"button\" id=\"bookBtn\">\r\n");
      out.write("								<img id=\"bookBtnImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bookmark.svg\"\r\n");
      out.write("									onclick=\"bookBtnClick()\">\r\n");
      out.write("							</button>\r\n");
      out.write("							<button type=\"button\" id=\"likeBtn\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/heart.svg\" id=\"likeBtnImg\"\r\n");
      out.write("									onclick=\"likeBtnClick()\">\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"alterBtn\">\r\n");
      out.write("							<button id=\"goToBtn\">목록으로</button>\r\n");
      out.write("							<button id=\"updateBtn\">수정</button>\r\n");
      out.write("							<button id=\"deleteBtn\">삭제</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/board/reply.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/board/board.js\"></script>\r\n");
      out.write("						<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/boardDatail.js\"></script>\r\n");
      out.write("\r\n");
      out.write("						<script>\r\n");
      out.write("							/* js에서 사용할 전역변수 */\r\n");
      out.write("							const contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("						</script>\r\n");
      out.write("		</body>\r\n");
      out.write("\r\n");
      out.write("		</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
