/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-27 11:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class secession_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원탈퇴</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/secession.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- 전체 컨테이너 -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- width 65%먹는 컨테이너 -->\r\n");
      out.write("        <div class=\"secon-container\">\r\n");
      out.write("            <center><b>회원탈퇴</b></center>\r\n");
      out.write("            <br>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <h3>01.회원탈퇴 안내</h3>\r\n");
      out.write("\r\n");
      out.write("            <!-- 탈퇴 약관 안내 -->\r\n");
      out.write("            <div class=\"terms\">\r\n");
      out.write("                Mixology 탈퇴안내 <br>\r\n");
      out.write("                안녕하세요.\r\n");
      out.write("                나가세요;\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"secession\" method=\"POST\" onsubmit=\"return secssionValidate()\">\r\n");
      out.write("                <div style=\"float: right;\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"agree\" id=\"agree\">\r\n");
      out.write("                    <label for=\"agree\">위 약관에 동의합니다.</label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                <h3>02. 회원탈퇴 하기</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 회원탈퇴 하기 -->\r\n");
      out.write("                    <div class=\"memOut\">\r\n");
      out.write("                        <!-- 비밀번호 -->\r\n");
      out.write("                    <div class=\"password\">\r\n");
      out.write("                        <div class=\"passwordC\"><b>비밀번호</b></div>\r\n");
      out.write("                        <!-- 비밀번호 input창 -->\r\n");
      out.write("                        <div id=\"passwordInput\"><input type=\"password\" id=\"memberPw\" name=\"memberPw\" style=\"height: 50%; width: 35%;\" placeholder=\"비밀번호를 입력해주세요.\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 탈퇴사유 -->\r\n");
      out.write("                    <div class=\"reason\">\r\n");
      out.write("                        <div class=\"outReason\"><b>탈퇴사유</b></div>\r\n");
      out.write("                        <!-- 탈퇴사유 checkbox -->\r\n");
      out.write("                        <div class=\"test\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"reason\" id=\"reasonNo\" value=\"reasonNo\">\r\n");
      out.write("                            <label for=\"reasonNo\"><b>없음</b></label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"reason\" id=\"useLow\" value=\"useLow\">\r\n");
      out.write("                            <label for=\"useLow\"><b>사용빈도 낮음</b></label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"reason\" id=\"contentLow\" value=\"contentLow\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"reason\" id=\"anything\" value=\"anything\">\r\n");
      out.write("                            <label for=\"contentLow\"><b>콘텐츠/정보부족</b></label>\r\n");
      out.write("                            <label for=\"anything\"><b>기타</b></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 남기실 말씀 -->\r\n");
      out.write("                    <div style=\"height: 200px;\">\r\n");
      out.write("                        <div class=\"outText\"><b>남기실 말씀</b></div>\r\n");
      out.write("                        <!-- 말씀 input -->\r\n");
      out.write("                        <div><textarea style=\"width: 100%;\"  placeholder=\"떠나시면서 소중한 의견을 남겨주세요.\"></textarea></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 홈 화면 가기 button -->\r\n");
      out.write("                <div class=\"back\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <button id=\"out\">탈퇴(진짜로..?ㅠ)</button>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- <div class=\"back\">\r\n");
      out.write("                <a href=\"\">\r\n");
      out.write("                    <button id=\"home\">홈 화면으로 가기</button>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'https://gist.githubusercontent.com/abs013r/cb774124e29ab7e396b638939ec0bda1/raw/479c0716a7104236e2e4fdc089586b3aeef5831b/MCnav.html',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            success: function(data) { $('#mc-nav').html(data); },\r\n");
      out.write("            error: function() { console.log('이거 뜨면 실패입니다… 조훈한테 문의하세요'); }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'https://gist.githubusercontent.com/abs013r/0d6ff4139684cf842192a2d312266a83/raw/6e629f95c437670fc573560fd8559829a25b30c8/MCfooter.html',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            success: function(data) { $('#mc-footer').html(data); },\r\n");
      out.write("            error: function() { console.log('이거 뜨면 실패입니다… 조훈한테 문의하세요'); }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/member/secession.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
