/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-26 02:04:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.column;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class column_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>컬럼 상세보기</title>\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/column.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 전체 컨테이너 -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- width 65%먹는 컨테이너 -->\r\n");
      out.write("        <div class=\"secon-container\">\r\n");
      out.write("                    <!-- 칵쓸신잡 배너-->\r\n");
      out.write("            <div id=\"banner\">\r\n");
      out.write("                <!-- 칵쓸신잡 배너 사진 -->\r\n");
      out.write("                <a href=\"columnAll.html\">\r\n");
      out.write("                    <img src=\"https://i.ibb.co/9ZDf4Jk/logo.png\" id=\"bannerPic\">\r\n");
      out.write("                </a>\r\n");
      out.write("            \r\n");
      out.write("                <!-- 칵쓸신잡 배너 글 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"banner1\" style=\"font-weight: bold;\">칵쓸신잡에서</p>\r\n");
      out.write("                    <p id=\"banner2\">칵테일에 대한 흥미로운 정보를 만나보세요</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 컬럼 제목 -->\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                [파격특가] 세계적 브랜드 로얄샬루트 98% 할인?!\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 올린 시간, 조회수 -->\r\n");
      out.write("            <div class=\"time\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>Mixology | 2023.07.10 17:44</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    조회수 132회\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 컬럼 헤드라인 -->\r\n");
      out.write("            <div class=\"head\">\r\n");
      out.write("                <h1>칵테일에 이런일이?</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 사진 -->\r\n");
      out.write("            <div class=\"picture\">\r\n");
      out.write("                <img src=\"/report/images/test.png\" id=\"colPic\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 글 타래 -->\r\n");
      out.write("            <div class=\"textCon\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        💘2023 서울바앤스피릿쇼 예약 바로가기💘\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    <p>\r\n");
      out.write("                        네이버 예약 - 서울바앤스피릿쇼 2023 (naver.com) \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <br>\r\n");
      out.write("                        \r\n");
      out.write("                    <p>\r\n");
      out.write("                        <2023 서울바앤스피릿쇼(이하 바앤쇼)>가 7월 28일부터 30일까지 서울 코엑스 D홀에서 열립니다. \r\n");
      out.write("                    </p>\r\n");
      out.write("                  \r\n");
      out.write("                    <p>\r\n");
      out.write("                        올해 바앤쇼에는 전시회장을 더욱 풍성하게 할 프로그램도 다수 준비되어 있다고 해요. \r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <p>\r\n");
      out.write("                        특히 국내 최상급 바 30여곳의 시그니처 칵테일🍸을 각 부스에서 맛볼 수 있는 '인피니티 바', \r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <p>\r\n");
      out.write("                        최정상 바텐더들의 경연 대회인 <span>'월드 칵테일 배틀'</span>🤴은 절대 빼놓지 말고 즐겨야 할 주요 콘텐츠예요. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        이외에도 '스마트 오더 파빌리온'에서 백술닷컴 등 주류에 대한 접근성과 편의성을 높이는 \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        다양한 브랜드의 면면도 살펴볼 수 있으니, 이번 행사도 절대 놓쳐서는 안 되겠지요?\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        바앤쇼에서 '백술닷컴'을 찾아보세요😎 깜짝 이벤트가 기다리고 있습니다!\r\n");
      out.write("                    </p>\r\n");
      out.write("                \r\n");
      out.write("                    <center>\r\n");
      out.write("                        <a href=\"columnAll.html\">\r\n");
      out.write("                             <button id=\"list\">\r\n");
      out.write("                                목록\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </center>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'https://gist.githubusercontent.com/abs013r/cb774124e29ab7e396b638939ec0bda1/raw/479c0716a7104236e2e4fdc089586b3aeef5831b/MCnav.html',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            success: function(data) { $('#mc-nav').html(data); },\r\n");
      out.write("            error: function() { console.log('이거 뜨면 실패입니다… 조훈한테 문의하세요'); }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'https://gist.githubusercontent.com/abs013r/0d6ff4139684cf842192a2d312266a83/raw/6e629f95c437670fc573560fd8559829a25b30c8/MCfooter.html',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            success: function(data) { $('#mc-footer').html(data); },\r\n");
      out.write("            error: function() { console.log('이거 뜨면 실패입니다… 조훈한테 문의하세요'); }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
