/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-24 07:49:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.column;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class columnAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>칼럼 전체보기 창</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/columnAll.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav id=\"mc-nav\"></nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- 전체 브라우저 container -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 컨텐츠 감싸는 container -->\r\n");
      out.write("    <div class=\"secon-container\">\r\n");
      out.write("        <!-- 칵쓸신잡 배너-->\r\n");
      out.write("        <div id=\"banner\">\r\n");
      out.write("            <!-- 칵쓸신잡 배너 사진 -->\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <img src=\"https://i.ibb.co/9ZDf4Jk/logo.png\" id=\"bannerPic\">\r\n");
      out.write("            </a>\r\n");
      out.write("           \r\n");
      out.write("             <!-- 칵쓸신잡 배너 글 -->\r\n");
      out.write("             <div>\r\n");
      out.write("                 <p id=\"banner1\" style=\"font-weight: bold;\">칵쓸신잡에서</p>\r\n");
      out.write("                 <p id=\"banner2\">칵테일에 대한 흥미로운 정보를 만나보세요</p>\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 배너랑 칼럼 사이 검색 창 -->\r\n");
      out.write("        <div id=\"searchArea\">\r\n");
      out.write("            <!-- 검색 목록 선택 -->\r\n");
      out.write("            <select name=\"title\" id=\"SearchOption\">\r\n");
      out.write("                <option value=\"title\">제목</option>\r\n");
      out.write("                <option value=\"content\">내용</option>\r\n");
      out.write("                <option value=\"TC\">제목 + 내용</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <!-- 검색 input -->\r\n");
      out.write("            <input type=\"text\" name=\"\" id=\"search\" placeholder=\"원하는 정보를 입력하세요!\">\r\n");
      out.write("            <!-- 검색 버튼 -->\r\n");
      out.write("            <button id=\"searchBtn\">검색</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 칼럼 영역 -->\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <div class=\"a\">\r\n");
      out.write("                <!-- 칼럼 사진 div -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- 칼럼 사진 -->\r\n");
      out.write("                    <a href=\"/report/html/column.html\">\r\n");
      out.write("                        <img src=\"/report/images/test.png\" id=\"test2\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 칼럼 제목 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"colName\">칵테일에 이런일이?</p>\r\n");
      out.write("                    <p id=\"colPreview\">운영진</p>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"a\">\r\n");
      out.write("                <!-- 칼럼 사진 div -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- 칼럼 사진 -->\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99654D335A07F4DA1E\" id=\"test2\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 칼럼 제목 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"colName\">칵테일이란?</p>\r\n");
      out.write("                    <p id=\"colPreview\">운영진</p>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"a\">\r\n");
      out.write("                <!-- 칼럼 사진 div -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- 칼럼 사진 -->\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99D04A335A07F4352E\" id=\"test2\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 칼럼 제목 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"colName\">칵테일이란?</p>\r\n");
      out.write("                    <p id=\"colPreview\">운영진</p>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 칼럼 영역 사이 빈칸 -->\r\n");
      out.write("        <div id=\"null\"></div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 칼럼 영역(두번째 줄) -->\r\n");
      out.write("         <div class=\"content\">\r\n");
      out.write("            <div class=\"a\">\r\n");
      out.write("                <!-- 칼럼 사진 div -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- 칼럼 사진 -->\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F990B86335A07F47B25\" id=\"test2\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 칼럼 제목 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"colName\">칵테일이란?</p>\r\n");
      out.write("                    <p id=\"colPreview\">운영진</p>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"a\">\r\n");
      out.write("                <!-- 칼럼 사진 div -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- 칼럼 사진 -->\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"https://i.ibb.co/9ZDf4Jk/logo.png\" id=\"test2\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 칼럼 제목 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"colName\">칵테일이란?</p>\r\n");
      out.write("                    <p id=\"colPreview\">운영진</p>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"a\">\r\n");
      out.write("                <!-- 칼럼 사진 div -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- 칼럼 사진 -->\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <img src=\"https://i.ibb.co/9ZDf4Jk/logo.png\" id=\"test2\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 칼럼 제목 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p id=\"colName\">칵테일이란?</p>\r\n");
      out.write("                    <p id=\"colPreview\">운영진</p>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 페이지 넘기기 -->\r\n");
      out.write("        <div class=\"select\">\r\n");
      out.write("            <div><button id=\"pageCon1\"><</button></div>\r\n");
      out.write("            <div><button id=\"pageCon2\">1</button></div>\r\n");
      out.write("            <div><button id=\"pageCon2\">2</button></div>\r\n");
      out.write("            <div><button id=\"pageCon2\">3</button></div>\r\n");
      out.write("            <div><button id=\"pageCon1\">></button></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mc-footer\"></div iv>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("$.ajax({\r\n");
      out.write("    url: 'https://gist.githubusercontent.com/abs013r/cb774124e29ab7e396b638939ec0bda1/raw/479c0716a7104236e2e4fdc089586b3aeef5831b/MCnav.html',\r\n");
      out.write("    type: 'GET',\r\n");
      out.write("    success: function(data) { $('#mc-nav').html(data); },\r\n");
      out.write("    error: function() { console.log('이거 뜨면 실패입니다… 조훈한테 문의하세요'); }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$.ajax({\r\n");
      out.write("    url: 'https://gist.githubusercontent.com/abs013r/0d6ff4139684cf842192a2d312266a83/raw/6e629f95c437670fc573560fd8559829a25b30c8/MCfooter.html',\r\n");
      out.write("    type: 'GET',\r\n");
      out.write("    success: function(data) { $('#mc-footer').html(data); },\r\n");
      out.write("    error: function() { console.log('이거 뜨면 실패입니다… 조훈한테 문의하세요'); }\r\n");
      out.write("});\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
