/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-28 16:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookMark_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>북마크</title>\n");
      out.write("\n");
      out.write("    <link href=\"https://fonts.cdnfonts.com/css/segoe-ui-4\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bookMark.css\">\n");
      out.write("\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a5af36132e.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"../js/jquery-3.7.0.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"board-list\">\n");
      out.write("        <h1 class=\"board-name\">북마크</h1>\n");
      out.write("\n");
      out.write("        <div class=\"list-wrapper\">\n");
      out.write("            <table class=\"list-table\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>글번호</th>\n");
      out.write("                        <th>제목</th>\n");
      out.write("                        <th>작성자</th>\n");
      out.write("                        <th>작성일</th>\n");
      out.write("                        <th>조회수</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("\n");
      out.write("                <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>10</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\">10번째 게시글</a>\n");
      out.write("                        </td>\n");
      out.write("                        <td>유저일</td>\n");
      out.write("                        <td>2023-07-17</td>\n");
      out.write("                        <td>50</td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"pagination-area\">\n");
      out.write("            <ul class=\"pagination\">\n");
      out.write("                <li><a href=\"#\">&lt;&lt</a></li>\n");
      out.write("                <li><a href=\"#\">&lt;</a></li>\n");
      out.write("\n");
      out.write("                <li><a class=\"current\">1</a></li>\n");
      out.write("\n");
      out.write("                <li><a href=\"#\">2</a></li>\n");
      out.write("                <li><a href=\"#\">3</a></li>\n");
      out.write("                <li><a href=\"#\">4</a></li>\n");
      out.write("                <li><a href=\"#\">5</a></li>\n");
      out.write("                <li><a href=\"#\">6</a></li>\n");
      out.write("                <li><a href=\"#\">7</a></li>\n");
      out.write("                <li><a href=\"#\">8</a></li>\n");
      out.write("                <li><a href=\"#\">9</a></li>\n");
      out.write("                <li><a href=\"#\">10</a></li>\n");
      out.write("\n");
      out.write("                <li><a href=\"#\">&gt;</a></li>\n");
      out.write("                <li><a href=\"#\">&gt;&gt;</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form action=\"#\" method=\"get\" id=\"boardSearch\">\n");
      out.write("\n");
      out.write("            <select name=\"key\">\n");
      out.write("                <option value=\"t\">제목</option>\n");
      out.write("                <option value=\"c\">내용</option>\n");
      out.write("                <option value=\"tc\">제목+내용</option>\n");
      out.write("                <option value=\"w\">작성자</option>\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <input type=\"text\" name=\"query\" placeholder=\"검색어를 입력해주세요.\">\n");
      out.write("\n");
      out.write("            <button>검색</button>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"../js/bookmark.js\"></script>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
